### PR TITLE
fix mcmc_rhat() bug, add mcmc diagnostics _data() functions.

### LINKED ISSUE #105: Error when plotting values for a corr_matrix with mcmc_rhat
I am using `mcmc_rhat` to plot posterior rhats for a mixture model (full stan code is [here](https://gist.github.com/jburos/4ac5db7714e6be24318dd8ba911049f1)).

I came across an error when plotting results for the `corr_matrix` parameter `Omega`:
```r
> rhats <- bayesplot::rhat(fit, par = 'Omega')
> rhats
Omega[1,1] Omega[1,2] Omega[1,3] Omega[1,4] Omega[2,1] Omega[2,2] Omega[2,3]
       NaN  1.0029974  0.9983262  0.9986153  1.0029974        NaN  1.0001934
Omega[2,4] Omega[3,1] Omega[3,2] Omega[3,3] Omega[3,4] Omega[4,1] Omega[4,2]
 0.9983336  0.9983262  1.0001934        NaN  0.9994124  0.9986153  0.9983336
Omega[4,3] Omega[4,4]
 0.9994124        NaN
> bayesplot::mcmc_rhat(rhats[!is.nan(rhats)])
Error in factor(x, labels = names(sort(x))) :
  invalid 'labels'; length 12 should be 1 or 6
```

(note that the Omega rhats contain `NaN` values for the diagonal elements -- I'm excluding these in the call to `mcmc_rhat`).

The parameter `Omega` is defined as:
```
parameters {
    corr_matrix[C] Omega;        // degree of correlation among loading factors for each cell type
    vector<lower=0>[C] tau;      // scale for each cell type - multiplied (on diagonal) with Omega
    matrix<lower=0>[G, C] theta; // loading factors for each gene, for each cell type
    //vector[C] theta_mu;

    vector[G] log_gene_base;     // constant intercept expression level for each gene, irrespective of cell type
    vector<lower=0>[G] gene_sd;  // stdev parameter per transcript (for now)

    simplex[C] sample2_x[S2];     // inferred sample2 compositions (simplex type enforces sum-to-one)
}
```

And my sessionInfo is:

```r
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] bindrcpp_0.2         bayesplot_1.3.0      glue_1.1.1
 [4] doParallel_1.0.10    iterators_1.0.8      foreach_1.4.3
 [7] lubridate_1.6.0      rstan_2.16.2         StanHeaders_2.16.0-1
[10] ggplot2_2.2.1        forcats_0.2.0        readr_1.1.1
[13] tidyr_0.7.0          dplyr_0.7.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     compiler_3.3.2   plyr_1.8.4       bindr_0.1
 [5] tools_3.3.2      digest_0.6.12    tibble_1.3.3     gtable_0.2.0
 [9] pkgconfig_2.0.1  rlang_0.1.2      gridExtra_2.2.1  stringr_1.2.0
[13] hms_0.3          stats4_3.3.2     grid_3.3.2       tidyselect_0.1.1
[17] inline_0.3.14    R6_2.2.2         reshape2_1.4.2   purrr_0.2.3
[21] magrittr_1.5     scales_0.4.1     codetools_0.2-15 assertthat_0.2.0
[25] colorspace_1.3-2 labeling_0.3     stringi_1.1.5    lazyeval_0.2.0
[29] munsell_0.4.3
```

The error appears to arise from `diagnostic_data_frame(x = rhat, diagnostic = "rhat")`, due to the fact that the correlation matrix contains 6 identical pairs of values (since the matrix is symmetrical) leading to a mismatch between the length of the `labels` and the number of levels.

Specifically, if I do:
```r
> factor(rhats[!is.nan(rhats)])
       Omega[1,2]        Omega[1,3]        Omega[1,4]        Omega[2,1]
 1.00299737566108 0.998326220064512 0.998615338525427  1.00299737566108
       Omega[2,3]        Omega[2,4]        Omega[3,1]        Omega[3,2]
 1.00019342981156 0.998333564304976 0.998326220064512  1.00019342981156
       Omega[3,4]        Omega[4,1]        Omega[4,2]        Omega[4,3]
0.999412432819772 0.998615338525427 0.998333564304976 0.999412432819772
6 Levels: 0.998326220064512 0.998333564304976 ... 1.00299737566108
```

I have 6 levels, not 12. This leads to an error within `diagnostic_data_frame` where the code reads:

```r
    fac <- if (!is.null(names(x))) {
        factor(x, labels = names(sort(x)))  # <--- here 
    }
    else {
        factor(x)
    }
```

Since we probably don't want parameters equivalent by definition to be plotted twice, an easy way to get around this is to first de-dup the elements of x, IE:
```r
x <- x[!duplicated(x)]
```

For example, if I run the above-mentioned `mcmc_rhat` code on `rhat[!duplicated(rhat)]` the code completes without error & I see the correct plot output.

### PR DESCRIPTION
**Pull request by tjmahr**
closes #105

### CODE REVIEW

File: R/mcmc-diagnostics.R [hunk 1]
```diff
@@ -280,6 +280,14 @@ mcmc_neff_hist <- function(ratio, ..., binwidth = NULL) {
     yaxis_ticks(FALSE)
 }
 
+#' @rdname MCMC-diagnostics
+#' @export
+mcmc_neff_data <- function(ratio, ...) {
```
Comment (jgabry) [inline R/mcmc-diagnostics.R:276]: Second time `mcmc_neff_data` is defined.

**Comment by jgabry** [comment]
@tjmahr Actually don't worry about removing one of the `mcmc_neff_data` definitions. I can just take care of that now while I'm working on bayesplot stuff.
